### ISSUE TITLE
No sia-ant executable, only sia-antfarm

### ISSUE THREAD

**Issue by mavlGlobant** [NebulousLabs/Sia-Ant-Farm#53]
Hi!
Acording to the instructions in the README file, I've downloaded and compiled the project, both in windows and linux and in none of them i get the **sia-ant.exe** / **sia-ant** executable, only **sia-antfarm.exe** / **sia-antfarm**.

Is it correct?

Thanks in advance.

**Comment by johnathanhowell** [comment]
Yes, the architecture of this has changed slightly. There is now only one executable.

**Comment by mavlGlobant** [comment]
Ok. Thank You.

**Comment by johnathanhowell** [comment]
Readme has been updated, see #54
