### ISSUE TITLE
ant-farm should test ant synchronization

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-Ant-Farm#8]
the ant farm should be able to automatically detect if the ants are on different blockchains. That's a little tricky I think because the ants will only ever tell you their most recent block, and it makes sense that the ants would be off by 1 or 2 blocks infrequently. Maybe the `consensus` call should be modified to return the 10 most recent blocks. That will make forks much more obvious to the farm.

**Comment by johnathanhowell** [comment]
This is now implemented.
